import Head from 'next/head';
import Image from 'next/image';
import Link from "next/link";
import styles from '@/styles/Home.module.css';
import fetch from 'isomorphic-unfetch';
import ItemsNavigationMenu from '@/components/itemsNavigation/ItemsNavigation';
import MainHeader from '@/components/MainHeader/MainHeader';
import Footer from '@/layout/Footer/Footer';

const ItemsPage = ({image, mainTitle, page}: any) => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="max-w-screen-2xl mx-auto my-0 bg-white px-10">
        <MainHeader renderMainTitle={mainTitle.data.attributes.title}/>

        <main className="mx-auto max-w-screen-2xl">
          <h1 className="mx-auto my-24 max-w-sm text-center font-bold text-4xl">
            {page.data.attributes.title}
          </h1>

          <ItemsNavigationMenu />
        </main>

        <Footer />
      </div>
    </>
  );
}

export default ItemsPage;

export const getStaticProps = async () => {
  const {NEXT_PUBLIC_STRAPI_URL} = process.env;

  const pagesResult = await fetch(`${NEXT_PUBLIC_STRAPI_URL}/api/pages/1?populate=deep`);
  const dataPage = await pagesResult.json();

  const image = `${NEXT_PUBLIC_STRAPI_URL}`+ dataPage.data.attributes.image.data.attributes.formats.medium.url;

  const siteResult = await fetch(`${NEXT_PUBLIC_STRAPI_URL}/api/annual-report`);
  const dataSite = await siteResult.json();
  
  return {
    props: {
      image,
      mainTitle: dataSite,
      page: dataPage,
    },
  };
};
